### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by paramsiddharth** [yeswehack/vulnerable-code-snippets#1]
Dockerizing the project would make it easier for people to run the snippets without installing PHP or MySQL on their systems.

We can potentially use Docker Compose to make it even easier.

**Comment by brumensywh** [comment]
Hey [paramsiddharth](https://github.com/paramsiddharth),

Great idea, I will get this working in the near future!

Regards,
YesWeHack / Brumens

**Comment by paramsiddharth** [comment]
> Hey [paramsiddharth](https://github.com/paramsiddharth),
> 
> Great idea, I will get this working in the near future!
> 
> Regards, YesWeHack / Brumens

Anytime. :) I'm an open-source contributor so if you need me to help with this, I'll be happy to.

**Comment by brumensywh** [comment]
Hey!

I just want to let you know that I haven't forgot the request and started on a sketch how to set it up in a way that works good for all the snippets. 
I'm unsure when but it will be released, but it's very likely to be done in a later version of the repo.

Best Regards,
Brumens

**Comment by paramsiddharth** [comment]
> Hey!
> 
> I just want to let you know that I haven't forgot the request and started on a sketch how to set it up in a way that works good for all the snippets. I'm unsure when but it will be released, but it's very likely to be done in a later version of the repo.
> 
> Best Regards, Brumens

No worries! Thank you for the ping. I'll be happy to keep in touch and help if needed.

I once conducted a Cybersecurity Workshop and I Dockerized all the examples in a similar way as we might intend to do here, so if you'd like to have a look, here's the repository: http://github.com/paramsiddharth/cybersec-workshop

Sincerely yours.
– Param Siddharth.

**Comment by brumensywh** [comment]
Sorry for the delay in your request.

Good news, the future Vsnippet will now be able to run in a docker!

Thank you for your suggestion!

Kind Regards,
- Brumens
