### ISSUE TITLE
Unable to access the vulnerable snippets

### ISSUE THREAD

**Issue by babyhacker0x7** [yeswehack/vulnerable-code-snippets#12]
![2024-10-31_15-34](https://github.com/user-attachments/assets/80d862ef-1195-4cdd-8aa9-5ee4143d4eaf)

**Comment by brumensywh** [comment]
Hey,

Thanks for the report, I have verified the issue and working on a fix to solve this!

Regards,
Brumens

**Comment by babyhacker0x7** [comment]
Please let me know after your fix. Thanks in advance.

**Comment by brumensywh** [comment]
Hey,
My mistake I re-read the code, you do get a response but it's empty, which means it is up, you need to add the 'q' GET parameter as shown in the source code. You can do this with the curl command: `curl http://localhost:1337/?q=123`

**Comment by brumensywh** [comment]
.

**Comment by brumensywh** [comment]
Hey,
My mistake I re-read the code, you do get a response but it's empty, which means it is up, you need to add the 'q' GET parameter as shown in the source code. You can do this with the curl command:
```shell
curl http://localhost:1337/?q=123
```
